Workiva/w-mobile-kit

README.md
WMobileKit.podspec

Description
---
Update the podspec in mobile kit to match the pubspec (as close as possible) specified here: https://wiki.atl.workiva.net/display/DEV/Open+Source+Software+-+OSS+-+External+Publishing+Process
---
- Updated podspec to workiva specifications
- Author name order is based on current contributions
Testing
---
1. Run ```pod lib lint --allow-warnings``` in the root and verify it passes
2. Verify everything was spelled correctly and looks professional/correct in ```WMobileKit.podspec```
---

MOBILE-2090: Update w-mobile-kit podspec to Workiva specifications

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

Releases that need to go out at the same time (if any): 
JIRA and PR's included in this release: 
======= w-mobile-kit 0.0.4 items =======
MOBILE-2090  - Update w-mobile-kit podspec to Workiva specifications  - https://github.com/Workiva/w-mobile-kit/pull/75
======= end =======
---

MOBILE-2086: RELEASE w-mobile-kit 0.0.4

---

Source/WSizeVC.swift

Description
---
- Fixing crash in the `WSizeVC`.
---
- Added a check to ensure constraints are only added when the view as been added
Testing
---
- Follow testing instruction in `wdesk-ios` repo.
---

MOBILE-2030: Adding check to prevent crash

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

Releases that need to go out at the same time (if any): 
JIRA and PR's included in this release: 
======= w-mobile-kit 0.0.5 items =======
MOBILE-2025  - Show LinkedIn profile picture in place of ALL user logos for the current user  - https://github.com/Workiva/w-mobile-kit/pull/76
MOBILE-2026  - Show LinkedIn profile picture for all users who have connected  - https://github.com/Workiva/w-mobile-kit/pull/76
MOBILE-2030  - UX improvements for unbound Tasks (not connected to a document)  - https://github.com/Workiva/w-mobile-kit/pull/78
======= end =======
---

MOBILE-2091: RELEASE w-mobile-kit 0.0.5

---

Example/Podfile.lock
Source/WActionSheet.swift
Tests/WActionSheetTests.swift

Description
---
Status bar changes color when action sheet is displayed (i.e. goes back to a grey status bar instead of white).
---
The UIWindow that gets created when an action sheet is shown now has a new rootViewController that solely manages the status bar style/hidden preference from the presenting view controller.
Testing
---
* Ensure unit tests pass
* Ensure on iOS 9 and iOS 10 that presenting an action sheet keeps the style of the status bar
* Can witness this in the Mobile Kit example app on iOS 10
* Can also copy the WActionSheet.swift file manually into the Wdesk app and verify it works as well on iOS 10 devices
---

MOBILE-2151: [iOS 10] Status bar changes color when action sheet is displayed

---

Example/Podfile.lock
Example/WMobileKitExample/SideMenuVCExample.swift
Source/WSideMenuVC.swift

Description
---
- Added swipe to open drawer with custom options.
---
- Added pan gesture with logic to handle the swipe to open and close the drawer.
- Added new options for the `WSideMenuVC`:
- `swipeToOpen`: The one flag that needs to be enabled to allow the user to swipe to open the drawer
- `swipeToOpenThreshold`: The percentage of the left side of the view used that can be swiped on and the drawer will open. Defaults to the left third.
- `autoOpenThreshold`: The percentage the drawer has to be swiped before it will automatically open. Defaults to halfway open.
Testing
---
1. Run the sample app and swiping to open the drawer from anywhere should work.
* Swiping right on the left third of the main view will start to open the drawer.
* Releasing before the drawer …

swipe-to-open: Adding swipe to open drawer with custom options

---

Source/WActionSheet.swift

Description
---
The action sheet currently shows the status bar according to the navigation controller or the presenting controller, but those aren't always in control of the status bar.
---
Status bar style for action sheets is now dictated by whatever the current style is no matter what view controller is controlling it
Testing
---
* Ensure when action sheets are presented in Mobile Kit, the status bar maintains its style
* Make the same diff manually in Wdesk and ensure the status bars maintain their style
---

MOBILE-2155: Action Sheet Status Bar Grabbing Incorrect Style

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

Releases that need to go out at the same time (if any): 
JIRA and PR's included in this release: 
======= w-mobile-kit 0.0.6 items =======
MOBILE-2155  - Action Sheet Status Bar Grabbing Incorrect Style  - https://github.com/Workiva/w-mobile-kit/pull/83
MOBILE-2155  - Action Sheet Status Bar Grabbing Incorrect Style  - https://github.com/Workiva/w-mobile-kit/pull/82
swipe-to-open: Adding swipe to open drawer with custom options  - https://github.com/Workiva/w-mobile-kit/pull/80
MOBILE-2151  - [iOS 10] Status bar changes color when action sheet is displayed.  - https://github.com/Workiva/w-mobile-kit/pull/81
======= end =======
---

MOBILE-2103: Version bump to 0.0.6

---

Example/Podfile.lock
Podfile
Podfile.lock
WMobileKit.podspec
smithy.sh
version_bump.sh

Description
---
The versions of the decencies in mobile-kit are not currently pinned down and causing issues since they are updating to newer versions of swift than we are currently compatible with. These should be pinned down in both the podfiles and the podspec. 
---
- Pinned down podspec libraries. 
- Bumped and pinned down testing libraries.
- Updated version bump script to update pods so both the library and example app pod files are kept up to date with each release.
- Added library validation to smithy.
Testing
---
1. Run ```./version_bump.sh 0.0.6 0.0.7```
2. Verify the version bump occurs on the correct files and both the main library and example app reflect the new changes to use 0.0.7 and any other pod updates.
3. Verify both pod installs use CryptoSwift 0.5.2 …

MOBILE-2160: Pin down mobile-kit dependencies in WMobileKit.podspec

---

Example/Podfile.lock
Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

Releases that need to go out at the same time (if any): 
JIRA and PR's included in this release: 
======= w-mobile-kit 1.0.0 items =======
MOBILE-2160  - Pin down mobile-kit dependencies in WMobileKit.podspec  - https://github.com/Workiva/w-mobile-kit/pull/85
======= end =======
---

MOBILE-2157 RELEASE w-mobile-kit 1.0.0

---

Example/WMobileKitExample/ModalViewExamplesVC.swift
Source/WBanner.swift

Description
---
A WBanner without the left icon has bad title padding.
---
Fixed padding issue when there is no title icon in a WBanner
Testing
---
* Run example app, verify the bottom banner example (that no longer has a title icon) shows correct padding for the title
---

MOBILE-2163: WBanner title has bad padding if no left icon.

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

* [MOBILE-2163: WBanner title has bad padding if no left icon.](https://github.com/Workiva/w-mobile-kit/pull/90)
Requested by: charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/1.0.0...version-bump-w-mobile-kit-1-0-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/1.0.0...1.0.1

MOBILE-2162 Release w-mobile-kit 1.0.1

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

* [MOBILE-2159: iOS: Update w-mobile-kit to swift 2.3](https://github.com/Workiva/w-mobile-kit/pull/89)
Requested by: charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/1.0.1...version-bump-w-mobile-kit-2-0-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/1.0.1...2.0.0

MOBILE-2164 Release w-mobile-kit 2.0.0

---

Source/WSwitch.swift

Description
---
Added a flag to WSwitch that controls sending ValueChanged event
---
- New shouldSendActionEvent flag
- New optional parameter to setOn that defaults to true
Testing
---
Use sample app to verify setting flag to false will not send a ValueChanged event and setting flag to true will.
---

MOBILE-2119: Flag to WSwitch that controls sending ValueChanged event

---

Source/WSpinner.swift
Tests/WSpinnerTests.swift

[PullToRefresh CR](https://github.com/Workiva/PullToRefresh/pull/1)
[Wdesk-ios CR](https://github.com/Workiva/wdesk-ios/pull/1231)
Description
---
- "Pull to refresh" components need to be less sensitive to pulling.
---
- Forked the `PullToRefresh` repo and added a `refreshingOffset` which increases the amount of you have to pull the table view to get the refresh to trigger by the height of the refresh view plus the new offset value.
- Added a direction to the `WSpinner` that will allow it to draw clockwise or counterclockwise.
- Inverted the colors of the background and the progress stroke layer of the `WSpinner` use in the `WPullToRefresh` and the indeterminate is now `0.85` instead of `0.15`. These changes are for allowing the stroke of the circle while pulling a …

MOBILE-1822: "Pull to refresh" components need to be less sensitive to pulling.

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

* [MOBILE-1822: "Pull to refresh" components need to be less sensitive to pulling.](https://github.com/Workiva/w-mobile-kit/pull/94)
* [MOBILE-2119: Flag to WSwitch that controls sending ValueChanged event](https://github.com/Workiva/w-mobile-kit/pull/95)
Requested by: charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/2.0.0...version-bump-w-mobile-kit-2-0-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/2.0.0...2.0.1

MOBILE-2165 Release w-mobile-kit 2.0.1

---

Source/WAutoCompleteTextView.swift
Source/WTextView.swift

[Connected wdesk-ios CR](https://github.com/Workiva/wdesk-ios/pull/1238)
Description
---
- Update AutoCompleteTextView to work with color-defined mentions by allowing it to accept changes in the form of Attributed Strings
---
- Added a second method for accepting attributed strings, as well as ensuring that textdidchange is triggered on attributedtext changes.
Testing
---
- Ensure that when using the AutoCompleteTextView in a situation that makes use of attributed strings, the proper attributes (colors, font, so forth) come through as expected, such as when inserted user mentions. 
---

[MOBILE-2175] Update AutoCompleteTextView to support AttributedStrings

---

Source/WSideMenuVC.swift

Description
---
The side menu button did not have an accessibility identifier causing automation tests to be difficult if the icon changes
---
Added accessibility identifier to the side menu button
Testing
---
* Ensure unit tests continue to pass
---

MOBILE-2197: Add accessibility identifier to the side menu button

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

* [MOBILE-2197: Add accessibility identifier to the side menu button](https://github.com/Workiva/w-mobile-kit/pull/100)
Requested by: charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/2.0.2...version-bump-w-mobile-kit-2-0-3_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/2.0.2...2.0.3

MOBILE-2201 Release w-mobile-kit 2.0.3

---

Example/Podfile.lock
Source/WUserLogoView.swift

Description
---
When running `pod lib lint` in Mobile Kit it won't release with compiler warnings unless a force flag is set. There are 4 warnings at time of this ticket creation. These should all be able to be addressed.
---
* There was just one left, so I changed it to a nil check.
```
-> WMobileKit (2.0.3)
- WARN  | xcodebuild:  /Users/jeffscaturro/workspaces/wf/w-mobile-kit/Source/WUserLogoView.swift:173:16: warning: value 'profileImage' was defined but never used; consider replacing with boolean test
```
Testing
---
---

[MOBILE-2104] Clean up last lint warning.

---

Source/WPagingSelectorVC.swift
Tests/WPagingSelectorVCTests.swift

Description
---
There was no proper way to set the page of a paging selector vc programmatically, which is required for deep linking changes in the Wdesk app.
---
* Added public setPage method which accepts an integer parameter to set the current tab
* Changed timing of a few property sets so that as soon as a tab starts changing, thats the new currentTab
Testing
---
* Target this branch in the podfile in the Wdesk iOS app
* Verify deep links to different pages/tabs work as expected
---

MOBILE-2253: Allow page to be set programmatically

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

* [[MOBILE-2104] Clean up last lint warning.](https://github.com/Workiva/w-mobile-kit/pull/102)
* [Readme_gifs: Added gifs to demo components and descriptions](https://github.com/Workiva/w-mobile-kit/pull/103)
* [[RED-659] Add Aviary.yaml](https://github.com/Workiva/w-mobile-kit/pull/104)
* [MOBILE-2253: Allow page to be set programmatically](https://github.com/Workiva/w-mobile-kit/pull/105)
Requested by: @charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/2.0.3...version-bump-w-mobile-kit-2-0-4
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/2.0.3...2.0.4

MOBILE-2247 Release w-mobile-kit 2.0.4

---

Source/WPanel.swift
Tests/WPanelTests.swift

Description
---
When you are on an iPad and open the WPanel, it starts as a side panel, then if you start multitasking and it changes to a vertical panel, the panel disappears and the fab isn't visible.
---
- When switching from side panel to vertical panel, it defaults to the smallest "ratio" above 0.0
- The view that intercepts the pan gesture to move the panel around is hidden when the panel isn't visible, to prevent the panel from being slid out even if the fab is hidden
Testing
---
* Open panel in side panel, multitask to half the screen, ensure the panel changes to vertical panel as expected
* Ensure you cannot slide the panel out without clicking the FAB
---

MOBILE-2325: Panel hides when opened as side panel, then multitasking changes to vertical panel

---

Example/Podfile.lock
Example/WMobileKitExample/PanelExample.swift
Source/WFAButton.swift
Source/WPanel.swift
Tests/WPanelTests.swift

Description
---
The panel in the viewer should have a minimum height to snap to
---
Added minimum height property to WPanel in case panel content needs to be larger than what is typically shown on smaller screen sizes
Testing
---
* Run example app on small and large screen sizes
- Verify the 3rd page on the Panel example always shows the entire content (AKA, the panel snaps to minimum height)
* Ensure unit tests pass
---

[MOBILE-2342] Panel should have minimum height to snap to

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

* [MOBILE-2355: Increase Radiobutton performance for use in Certs](https://github.com/Workiva/w-mobile-kit/pull/115)
* [[MOBILE-2342] Panel should have minimum height to snap to](https://github.com/Workiva/w-mobile-kit/pull/113)
Requested by: @jeffscaturro-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/2.1.2...version-bump-w-mobile-kit-2-1-3
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/2.1.2...2.1.3

MOBILE-2331 Release w-mobile-kit 2.1.3

---

smithy.yaml

In order to keep builds deterministic, and reduce the risk of future build failure, please pin your smithy runner to the currently defaulted runner.
For more information please see the email 'Smithy Runner Recommendation' or reach out to Travis Reed in hipchat.
Requested by: @travisreed-wf

RMCONS-5518 Consume smithy-runner 3.5.5

---

Example/Podfile.lock
Gemfile.lock
Source/WPagingSelectorVC.swift
Tests/WPagingSelectorVCTests.swift

Description
---
View will reset when you change tabs:
```
1. Navigate from My Recent to the All Files tab in Wdesk mobile (note: this happens in Tasks, Certs, etc too)
2. Change to landscape mode
3. View resets to My Recents
```
I noticed a retain cycle in Wdesk (*slightly* difficult to reproduce, may have gotten it in a weirder state at first then noticed these steps to reproduce):
```
1. Start on All Files tab
2. Rotate
3. Tap Recent tab, tap All Files tab
4. Rotate
5. Repeat
6. The count will increase while doing this.
```
---
We were calling `setupUI` again on rotate or size class events, where I believe we just needed to update the constraints. I did not notice any regressions using this approach but would like original author's eyes on it.
* I broke the SnapKit …

[MOBILE-2425] Update constraints on constraint change.

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

* [RMCONS-5518 Consume smithy-runner 3.5.5](https://github.com/Workiva/w-mobile-kit/pull/123)
* [[MOBILE-2425] Update constraints on constraint change.](https://github.com/Workiva/w-mobile-kit/pull/127)
Requested by: @brianblanchard-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/2.1.4...version-bump-w-mobile-kit-2-1-5
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/2.1.4...2.1.5

MOBILE-2418 Release w-mobile-kit 2.1.5

---

smithy.yaml

* [DEVTOOLS-531: smithy builder updates](https://github.com/Workiva/smithy-runner/pull/29)

DEVTOOLS-957 Consume smithy-runner v3.6.2

---

Source/WRadioButton.swift
Tests/WRadioButtonTests.swift

Description
---
In order to support the changes requested in MOBILE-2521, we need the ability to have a different border color for when the radio button is selected and when it is not.
---
* Changed `borderColor` to now be two vars, `borderColorNotSelected` and `borderColorSelected`. 
* Added a method `updateUISelectedChanged` that updates the border color during setup and `selected`'s `didSet`.
* Added/refactored unit tests.
Testing
---
---

[MOBILE-2521] WRadioButton border selected v non-selected.

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

* [DEVTOOLS-957 Consume smithy-runner v3.6.2](https://github.com/Workiva/w-mobile-kit/pull/126)
* [[MOBILE-2521] WRadioButton border selected v non-selected.](https://github.com/Workiva/w-mobile-kit/pull/130)
Requested by: @jeffscaturro-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/2.1.5...version-bump-w-mobile-kit-2-1-6
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/2.1.5...2.1.6

MOBILE-2527 Release w-mobile-kit 2.1.6

---

Source/WActionSheet.swift
Source/WPagingSelectorVC.swift

Description
---
We needed accessibility ID's on some mobile kit components to improve reliability of functional tests in our Wdesk app
---
Added accessibilityIdentifiers to both action sheet tables and paging selector controls
- Paging selector control ID isn't used yet but can be utilized in future tests/improvements
Testing
---
Verify that MOBILE-2525 in Wdesk repo is passing using the action sheet accessibility ID
---

MOBILE-2525: Add Accessibility ID's for Functional Tests

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

* [MOBILE-2519: AutoViewLayoutVC](https://github.com/Workiva/w-mobile-kit/pull/132)
* [MOBILE-2525: Add Accessibility ID's for Functional Tests](https://github.com/Workiva/w-mobile-kit/pull/133)
Requested by: @jeffscaturro-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/2.1.6...version-bump-w-mobile-kit-2-1-7
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/2.1.6...2.1.7

MOBILE-2529 Release w-mobile-kit 2.1.7

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

* [MOBILE-2555: Upgrade to swift 3](https://github.com/Workiva/w-mobile-kit/pull/135)
Requested by: @brianblanchard-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/2.1.7...version-bump-w-mobile-kit-3-0-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/2.1.7...3.0.0

MOBILE-2547 Release w-mobile-kit 3.0.0

---

Example/Podfile.lock
Example/WMobileKitExample/UserLogoViewExamplesVC.swift
Source/WUserLogoView.swift
Tests/WUserLogoViewTests.swift

Description
---
Add square version of User Logo component to MobileKit
Acceptance Criteria:
----
1. Component should be customizable
2. Utilizes existing User Logo
---
Added two properties to WUserLogoView:
1. Type
- .Outline
- Default value, only draws outline of shape, font matches color of mapped color
- .Filled
- Will fill in the whole shape, change font to a bolded white color
- Also with a customizable corner radius
2. Shape
- .Circle
- Default value, draws a circle like normal
- .Square
- Draws a square with rounded corners based on the cornerRadius property of WUserLogo, which has a default value of 3.0
Testing
---
- Ensure unit tests pass
- Look at example app and ensure all combinations of shapes, types, and images vs no images are represented and are fully …

MOBILE-2585: Create Square User Logo

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

* [MOBILE-2585: Create Square User Logo](https://github.com/Workiva/w-mobile-kit/pull/139)
Requested by: @jordanross-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/4.0.0...version-bump-w-mobile-kit-4-1-0_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/4.0.0...4.1.0

MOBILE-2573 Release w-mobile-kit 4.1.0

---

Example/Podfile.lock
Gemfile
Podfile
Podfile.lock
Source/WBadge.swift
Source/WBanner.swift
Tests/WBadgeTests.swift
WMobileKit.podspec
smithy.sh
smithy.yaml

Description
---
w-mobile-kit is currently hitting some collisions with the naming in Material library. This should be fixes and the library included to avoid future issues.
---
- Fixed a few naming collisions with certain extensions
Testing
---
1. Verify no functionality was changed
2. Unit tests pass. 
---

MOBILE-2612: Fix incompatibilities with Material Library

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

* [MOBILE-2612: Fix incompatibilities with Material Library](https://github.com/Workiva/w-mobile-kit/pull/141)
Requested by: @jeffscaturro-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/4.1.0...version-bump-w-mobile-kit-5-0-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/4.1.0...5.0.0

MOBILE-2603 Release w-mobile-kit 5.0.0

---

Source/WLoadingModal.swift
Source/WSideMenuVC.swift

Description
---
It was hard to subclass WLoadingModal and add changes necessary due to private declaration of the `commonInit` method.
The WSideMenuVC can only have one delegate so it was tricky to tap into when the drawer closes fully.
---
- WLoadingModal's `commonInit` was changed to `open` visibility
- WSideMenuVC's `closeDrawer` method now can accept a completion block called after the animation finishes.
Testing
---
Test in Wdesk iOS PR of `MOBILE-2589, 2615`
---

MOBILE-2615: Increase Mobile Kit flexibility

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

* [[MOBILE-2624] Increase flexibility of toast and action sheet](https://github.com/Workiva/w-mobile-kit/pull/145)
Requested by: @jamesromo-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/5.0.1...version-bump-w-mobile-kit-5-0-2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/5.0.1...5.0.2

MOBILE-2623 Release w-mobile-kit 5.0.2

---

Example/WMobileKitExample/Info.plist
Source/Info.plist
WMobileKit.podspec

* [MOBILE-2656: Xcode 9/Swift 3.2](https://github.com/Workiva/w-mobile-kit/pull/149)
* [[Update Readme] Update readme with links to source code.](https://github.com/Workiva/w-mobile-kit/pull/151)
Requested by: @jamesromo-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w-mobile-kit/compare/5.0.2...Workiva:release_w-mobile-kit_5_1_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w-mobile-kit/compare/5.0.2...5.1.0
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5659090173820928/logs/)

MOBILE-2642 Release w-mobile-kit 5.1.0

---

Gemfile.lock

**Problem:** There was a vulnerability found in `rubyzip <=1.2.1`.
https://nvd.nist.gov/vuln/detail/CVE-2018-1000544
**Solution:** Bump to `rubyzip >=1.2.2`.
@jamesromo-wf @jordanross-wf

SEC-17380 - Bumping rubyzip
